env:
  device: null                          # (None or str): specifies the device to be used if running on the gpu with torch backend
  automatic_reset: false                # (bool): whether to automatic reset after an episode finishes
  flatten_action_space: false           # (bool): whether to flatten the action space as a sinle 1D-array
  flatten_obs_space: false              # (bool): whether the observation space should be flattened when generated
  use_external_obs: false               # (bool): Whether to use external observations or not
  initial_pos_z_offset: 0.1
  external_sensors:                     # (None or list): If specified, list of sensor configurations for external sensors to add. Should specify sensor "type" and any additional kwargs to instantiate the sensor. Each entry should be the kwargs passed to @create_sensor, in addition to position, orientation
    - sensor_type: VisionSensor
      name: external_sensor0
      relative_prim_path: /external_sensor0
      modalities: [rgb, depth]
      sensor_kwargs:
        image_height: 128
        image_width: 128
      position: [0, 0, 1.0]
      orientation: [0.707, 0.0, 0.0, 0.707]
      pose_frame: parent


render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: InteractiveTraversableScene
  scene_model: Rs_int

robot:
  robot_config:
    name: Fetch
    type: Fetch
    obs_modalities: [rgb, depth]
    action_modalities: continuous
    action_normalize: False
    position: [-0.8, 0.0, 0.]
    grasping_mode: assisted

    controller_config:
      base:
        name: DifferentialDriveController
      arm_0:
        name: OperationalSpaceController
        kp: 250
        kp_limits: [50, 400]
        damping_ratio: 0.6
      gripper_0:
        name: MultiFingerGripperController
        command_input_limits: [0.0, 1.0]
        mode: smooth
      camera:
        name: JointController

objects: []

task:
  type: BehaviorTask
  activity_name: opening_doors
  activity_definition_id: 0
  activity_instance_id: 0
  predefined_problem: null
  online_object_sampling: false
  debug_object_sampling: null
  highlight_task_relevant_objects: false
  termination_config:
    max_steps: 500
  reward_config:
    r_potential: 1.0